sm_user:
    resource: "@SMUserBundle/Resources/config/routing.yml"
    prefix:   /

smssn:
    resource: "@SMSSNBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"